### ISSUE TITLE
resolve grid issue wrt CIM2 classes

### ISSUE THREAD

**Issue by eguil** [ES-DOC/cmip6-specializations-ocean#5]
Part of grid is in key_properties class and part in grid class.
Review why and solve in ocean specialisation
- I remember that discretisation should be separated from resolution

**Comment by davidhassell** [comment]
Some musings, lest I forget.

The `grid` seems to be not much more than a thin wrapper around a `discretisation`. Straw man proposal: Delete `grid` and add a "discretisation" property to `key_properties`, alongside the existing "resolution" and "extent" properties:

```
<snip>    
            ('extent', 'science.extent', '0.1',
                "DESCRIPTION."),
            ('resolution', 'science.resolution', '0.1',
                "The resolution of the grid (e.g. N512L180)."),
            ('discretisation', 'science.discretisation', '0.1',
                "Description of the numerics of the discretisation."),
<snip>
```

Cons? Can't share grids (but given how thin they'd become, were we ever going to?); The notion of a "grid" has gone from the CIM.

Pros? Easier to understand and enter information.

Another proposal: create a new `grid` which just contains `resolution`, `extent` and `discretisation`. This would be the value of a "grid" property if `key_properties`, and so would not be a stand-alone CIM document. This might address con #2 above.

Comments welcome (and expected, given my track record on grids today!)

**Comment by davidhassell** [comment]
OK. Discussed at face-to-face and no longer needed. Solution: resolution stuff to move from `grid` to `key_properties`
