### ISSUE TITLE
cpocean, rhozero dependence on CMIP6 data request

### ISSUE THREAD

**Issue by durack1** [ES-DOC/cmip6-specializations-ocean#9]
@eguil @momipsl I am wondering if you have any dependence on the `cpocean` and `rhozero` variables that are currently included in the OMIP data request?

We have these defined as required output fields in the physics: https://goo.gl/Rhrcwp (Ofx, lines 11 and 12) sheet (which defines the variables being requested), however, it seems this is also listed in [ES-DOC/cmip6-specializations-ocean/ocean_key_properties.py](https://github.com/ES-DOC/cmip6-specializations-ocean/blob/master/ocean_key_properties.py#L64-L67)

@martinjuckes would like these removed, but just checking to make sure there are no dependencies that will be broken if this change is made

https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/148

**Comment by eguil** [comment]
Hi Paul, yes these are indeed captured in ES-DOC/cmip6-specializations-ocean/ocean_key_properties.py and can go from the Data Request

**Comment by durack1** [comment]
@eguil thanks for this, @martinjuckes will remove them then.. I'll close this issue too
